# Generated by Django 4.2.25 on 2025-10-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_check_in', models.DateField(help_text='Ingrese Fecha de entrada')),
                ('fecha_check_out', models.DateField(help_text='Ingrese Fecha de salida')),
                ('estado_reserva', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('checkin', 'Check-in'), ('checkout', 'Check-out'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('numero_habitacion_temporal', models.CharField(blank=True, max_length=10, null=True)),
                ('Huespedes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.huesped')),
            ],
        ),
    ]
