# Generated by Django 4.1.13 on 2025-11-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_check_in', models.DateField(help_text='Ingrese Fecha de entrada')),
                ('fecha_check_out', models.DateField(help_text='Ingrese Fecha de salida')),
                ('estado_reserva', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=15)),
                ('Tipo_Habitacion', models.CharField(choices=[('SIMPLE', 'Simple'), ('DOBLE', 'Doble'), ('SUITE', 'Suite')], max_length=50)),
                ('pago_estancia', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto pagado por la estancia al momento del check-in.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Habitaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion')),
                ('Huespedes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.huesped')),
            ],
        ),
    ]
