# Generated by Django 4.2.25 on 2025-10-24 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_check_in', models.DateField(help_text='Ingrese Fecha de entrada')),
                ('fecha_check_out', models.DateField(help_text='Ingrese Fecha de salida')),
                ('estado_reserva', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('Estado_Habitacion', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENCION', 'En Mantención')], max_length=15)),
                ('Tipo_Habitacion', models.CharField(choices=[('SIMPLE', 'Simple'), ('DOBLE', 'Doble'), ('SUITE', 'Suite')], max_length=50)),
                ('Habitaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion')),
                ('Huespedes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.huesped')),
            ],
        ),
    ]
