# Generated by Django 4.2.25 on 2025-11-05 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroreservas',
            name='Estado_Habitacion',
        ),
        migrations.AddField(
            model_name='registroreservas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroreservas',
            name='pago_estancia',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto pagado por la estancia al momento del check-in.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='registroreservas',
            name='estado_reserva',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=15),
        ),
    ]
