# Generated by Django 4.1.13 on 2025-10-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_alter_habitacion_tipo'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroreservas',
            name='numero_habitacion_temporal',
        ),
        migrations.AddField(
            model_name='registroreservas',
            name='Estado_Habitacion',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENCION', 'En Mantención')], default='disponible', max_length=15),
        ),
        migrations.AddField(
            model_name='registroreservas',
            name='Habitaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion'),
        ),
        migrations.AddField(
            model_name='registroreservas',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Motivo por el cual se canceló la reserva.', null=True),
        ),
        migrations.AlterField(
            model_name='registroreservas',
            name='estado_reserva',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15),
        ),
    ]
