# Generated by Django 4.1.13 on 2025-11-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('SIMPLE', 'Simple'), ('DOBLE', 'Doble'), ('SUITE', 'Suite')], default='SIMPLE', max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('tarifa', models.PositiveIntegerField()),
                ('comodidades', models.TextField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENCION', 'En Mantención')], default='DISPONIBLE', max_length=15)),
            ],
        ),
    ]
