# Generated by Django 4.2.25 on 2025-10-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=15),
        ),
    ]
