# Generated by Django 4.2.25 on 2025-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
