# Generated by Django 4.1.13 on 2025-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('SENCILLA', 'Sencilla'), ('DOBLE', 'Doble'), ('SUITE', 'Suite')], default='SENCILLA', max_length=50),
        ),
    ]
