# Generated by Django 4.1.13 on 2025-10-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_alter_habitacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('SENCILLA', 'Sencilla'), ('DOBLE', 'Doble'), ('SUITE', 'Suite')], max_length=50),
        ),
    ]
